### ISSUE TITLE
Cannot run Graphql-qb over http://statistics.gov.scot/sparql

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#33] opened 2017-10-04 12:53 UTC
I try to run Graphql-qb over http://statistics.gov.scot/sparql

`java -jar graphql-qb-0.1.0-SNAPSHOT-standalone.jar --port 2222 --endpoint http://statistics.gov.scot/sparql`

And get the following exception:

```
Exception in thread "main" clojure.lang.ExceptionInfo: Error waiting on results {:prepared-query #object[org.openrdf.repository.sparql.query.SPARQLTupleQuery 0xc85a25 "PREFIX qb: <http://purl.org/linked-data/cube#>\r\nSELECT ?uri ?title ?description WHERE {\r\n  ?ds qb:structure ?struct .\r\n  ?ds <http://purl.org/dc/terms/title> ?title .\r\n  ?ds <http://www.w3.org/2000/01/rdf-schema#comment> ?description .\r\n  BIND(?ds as ?uri)\r\n}"]}
        at clojure.core$ex_info.invokeStatic(core.clj:4617)
        at clojure.core$ex_info.invoke(core.clj:4617)
        at grafter.rdf.repository$sesame_results__GT_seq$pull_query__1991.invoke(repository.clj:420)
        at grafter.rdf.repository$sesame_results__GT_seq.invokeStatic(repository.clj:421)
        at grafter.rdf.repository$sesame_results__GT_seq.invoke(repository.clj:402)
        at grafter.rdf.repository$fn__2018.invokeStatic(repository.clj:435)
        at grafter.rdf.repository$fn__2018.invoke(repository.clj:428)
        at grafter.rdf.repository$fn__2005$G__2000__2010.invoke(repository.clj:423)
        at grafter.rdf.sparql$query.invokeStatic(sparql.clj:141)
        at grafter.rdf.sparql$query.invoke(sparql.clj:92)
        at grafter.rdf.sparql$query.invokeStatic(sparql.clj:123)
        at grafter.rdf.sparql$query.invoke(sparql.clj:92)
        at graphql_qb.core$find_datasets.invokeStatic(core.clj:380)
        at graphql_qb.core$find_datasets.invoke(core.clj:379)
        at graphql_qb.core$build_schema_context.invokeStatic(core.clj:434)
        at graphql_qb.core$build_schema_context.invoke(core.clj:433)
        at graphql_qb.server$create_server.invokeStatic(server.clj:11)
        at graphql_qb.server$create_server.invoke(server.clj:8)
        at graphql_qb.server$start_server.invokeStatic(server.clj:19)
        at graphql_qb.server$start_server.invoke(server.clj:18)
        at graphql_qb.main$_main.invokeStatic(main.clj:45)
        at graphql_qb.main$_main.doInvoke(main.clj:36)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at graphql_qb.main.main(Unknown Source)
Caused by: org.openrdf.query.QueryEvaluationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 1, column: 2]
        at org.openrdf.http.client.QueueCursor.checkException(QueueCursor.java:170)
        at org.openrdf.http.client.QueueCursor.getNextElement(QueueCursor.java:125)
        at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
        at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
        at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
        at grafter.rdf.repository$sesame_results__GT_seq$pull_query__1991.invoke(repository.clj:409)
        ... 21 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
        at org.openrdf.query.resultio.sparqljson.SPARQLJSONParserBase.parseQueryResultInternal(SPARQLJSONParserBase.java:132)
        at org.openrdf.query.resultio.sparqljson.SPARQLJSONParserBase.parseQueryResult(SPARQLJSONParserBase.java:117)
        at org.openrdf.http.client.BackgroundTupleResult.run(BackgroundTupleResult.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by BillSwirrl** [comment] 2017-10-04 15:13
Hi Dimitris - thanks for all the issues.  For this one, looks like it might be a timeout.  Lee, who has been building the implementation, is on leave this week, back on Monday - so might need till then to solve this and some of the other issues

**Comment by BillSwirrl** [comment] 2017-10-04 15:18
the query listed in the exception is this:

```
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?uri ?title ?description WHERE {
?ds qb:structure ?struct .
?ds <http://purl.org/dc/terms/title> ?title .
?ds <http://www.w3.org/2000/01/rdf-schema#comment> ?description .
BIND(?ds as ?uri)
}
```
It runs quite quickly when I do it by hand via the sparql console, so in fact probably not a timeout.

**Comment by BillSwirrl** [comment] 2017-10-05 08:24
Hi @zeginis - Ric has explained the cause of this to me. It's a bug in Ruby on Rails content negotiation, which comes up when it is used together with Sesame.  Rails does not treat the quality values correctly: Sesame lists a wide range of things it can accept and Rails messes it up!  In this case the end result is that you ask for JSON and you get XML.

We are going to change the way this works in PublishMyData, so the problem will go away, but possibly not for a while.

We have a work-around - I'll email you about that.

**Comment by RickMoynihan** [comment] 2017-10-09 13:51
This should all be fixed now.

For future reference the URL of the scotland SPARQL endpoint is: `https://production-drafter-sg.publishmydata.com/v1/sparql/live`

**Closed by RickMoynihan** 2017-10-09 13:51 UTC

**Comment by RickMoynihan** [comment] 2017-10-09 14:06
@zeginis Now that this should be working, you should be able to run this against other "compatible" cubes.

I'm curious if you're planning to run this on any other endpoints/datasets, and if so which ones...  It would be useful if you could try running what we have against data you have to highlight any issues we might have at this stage.  If you find any issues if you could report them back on new tickets as appropriate it might be useful.

We know for example there are issues with the multiple measure property styles still left to resolve e.g. #34.
