### ISSUE TITLE
Missing and replicated cubes in api response

### ISSUE THREAD

**Issue by mohadelrezk** [Swirrl/graphql-qb#83] opened 2018-04-16 17:35 UTC
API not returning all existing datasets on our rdf store. instead it replicates some of them on the query results. 

http://vmogi01.deri.ie:8002/index.html?variables=null&query=%7B%0A%20%20datasets%20%7B%0A%20%20%20%20uri%0A%20%20%7D%0A%7D%0A

![screen shot 2018-04-16 at 15 56 37](https://user-images.githubusercontent.com/17986166/38825516-c4a27d8c-41a4-11e8-9092-2474df5795ea.png)

(tested against sparql queries to same rdf datastore) 

![screen shot 2017-12-08 at 12 56 39](https://user-images.githubusercontent.com/17986166/38825536-d694b438-41a4-11e8-957d-521470faecd8.png)

**Comment by zeginis** [comment] 2018-04-18 10:59
The API currenlty assumes that the dataset has an rdfs:label and there is only one dcterms:publisher.
- Do all your datasets have an rdfs:label?
- I see that the datasets that are dublicate have 2 dcterms:publishers that's why they appear twice 

The SPARQL executed to get the datasets is the following. Can you run it directly to your SPARQL endpoint?

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?ds ?title ?description ?licence ?issued ?modified ?publisher WHERE {
   ?ds a qb:DataSet .
   ?ds rdfs:label ?title .
   OPTIONAL { ?ds rdfs:comment ?description . }
   OPTIONAL { ?ds dcterms:license ?licence }
   OPTIONAL { ?ds dcterms:issued ?issued }
   OPTIONAL { ?ds dcterms:modified ?modified }
   OPTIONAL { ?ds dcterms:publisher ?publisher }
}
```

**Comment by mohadelrezk** [comment] 2018-04-19 15:29
Datasets have rdfs:label, And have tow publishers as well.
following result of the query against my endpoint, it is redundant but have all datasets:

![screen shot 2018-04-19 at 16 24 22](https://user-images.githubusercontent.com/17986166/39001661-b8bf9990-43ee-11e8-82ec-a6bf1a044a9a.png)
![screen shot 2018-04-19 at 16 24 51](https://user-images.githubusercontent.com/17986166/39001662-b8d8ce60-43ee-11e8-9ce0-29f03858677c.png)
![screen shot 2018-04-19 at 16 25 00](https://user-images.githubusercontent.com/17986166/39001663-b8f1f958-43ee-11e8-9e76-83dbb69d70a7.png)
![screen shot 2018-04-19 at 16 25 09](https://user-images.githubusercontent.com/17986166/39001664-b909b1b0-43ee-11e8-84da-0c7d9be55201.png)



.

**Comment by mohadelrezk** [comment] 2018-06-11 14:39
@zeginis you might try **distinct**  this could solve this issue.

**Comment by zeginis** [comment] 2018-06-11 15:33
@mohadelrezk is you SPARQL endpoint publicly available in order to replicate the issue and debug?

**Comment by mohadelrezk** [comment] 2018-06-12 09:57
@zeginis will email you endpoint details

**Comment by zeginis** [comment] 2018-06-20 15:30
@mohadelrezk  I run the query directly to your SPARQL endpoint and there are duplicates due to the 2 dcterms:publishers defined at the cube. Distinct will not solve this. You can try removing one the publishers and check again.

Curently CubiQL assumes that each dataset has only one:
-  rdfs:comment
- dcterms:license
- dcterms:issued 
- dcterms:modified and
- dcterms:publisher

If this is not the case then we should also handle multiple values for the above properties.

**Comment by zeginis** [comment] 2018-06-29 12:51
Duplicate results are also returned for Scotish data due to multiple "Date Issued". 
E.g. The data set http://statistics.gov.scot/data/gross-value-added has two Issued Dates.

**Comment by mohadelrezk** [comment] 2018-06-29 15:52
We consider us and the pilot are the dataset publishers.
I think this would be a common case for published datasets and need to be considered in the implementation.

**Comment by RickMoynihan** [comment] 2018-07-03 11:48
Closing this issue as the cause is multiple values on some of the properties.  I've split this issue up into #96 and #97.  On the call it was mentioned that the missing datasets thing was no longer a problem, but if it turns out to be please open a new issue for it.

@zeginis: Please can you clear out the project boards and put these issues (and #6) in the TODO column.

**Closed by RickMoynihan** 2018-07-03 11:48 UTC
