### ISSUE TITLE
Aggregations return zero or null values

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#62] opened 2017-12-04 16:28 UTC
e.g. zero value:

```
{  dataset_earnings {
     observations(dimensions: {gender: ALL, 
                              population_group: WORKPLACE_BASED, 
                              measure_type: MEDIAN}) {
      aggregations {
        sum(measure:MEDIAN)
}}}}
```

Null value:
```
{dataset_earnings {
     observations(dimensions: {gender: ALL, 
                              population_group: WORKPLACE_BASED, 
                              measure_type: MEDIAN}) {
      aggregations {
        min(measure: MEDIAN)
      }}}}
```

**Comment by lkitching** [comment] 2017-12-06 11:29
Can't reproduce this locally on `master`. This should be fixed in 8f42fbdc6e35921f4fcc69b1351ea77934b2f53f which is not in the currently-deployed version.

**Closed by lkitching** 2017-12-06 11:29 UTC
